App\Entity\Exhibit:
  attributes:
    code:
      groups: ['Default', 'playlist']
    title:
      groups: ['Default', 'playlist']
    description:
      groups: ['Default', 'playlist']
    s3Url:
      groups: ['playlist']
